# S3 bucket to store template
- s3_bucket:
    name: "{{ stack }}-cf-templates"
    state: present
    region: "{{ region }}"
    profile: "{{ aws_profile }}"
  register: s3_template_bucket

- s3: 
    bucket: "{{ stack }}-cf-templates"
    object: "cloudfront.yml" 
    src: "../../templates/{{ cf_template }}.yml"
    mode: put
    region: "{{ region }}"
    profile: "{{ aws_profile }}"
  register: s3_object
  tags: "cloudformation-s3upload"

- include: web-standard.yml
  when: cf_template == 'web-standard'

- include: web-stage-prod.yml
  when: cf_template == 'web-stage-prod'

- debug: var=cf
