---
- name: Create S3 bucket to store CF template
  s3_bucket:
    name: "{{ stack }}-cf-templates"
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
  register: s3_template_bucket

- name: Upload CF template to S3
  aws_s3: 
    bucket: "{{ stack }}-cf-templates"
    object: "cloudfront.yml" 
    src: "{{ role_path }}/files/{{ cf_template }}.yml"
    mode: put
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
  register: s3_object
  tags: "cloudformation-s3upload"

# Include CF template-specific task
- include: "{{ cf_template }}.yml"

- debug: var=cf
